"""The documentation site (issue #33): every Python example runs, and the generated reference pages are current.

``tests/conformance/test_docs_examples.py`` runs the examples that need the official artifacts too.
"""

import os
import re

import _docs
import _markdown_doctest
from euinvoice.validation import artifacts

ARTIFACTS_PAGE = _docs.DOCS / "reference" / "artifacts.md"


def test_every_page_with_code_is_run() -> None:
    assert _docs.pages_with_code() == set(_docs.PAGES)


def test_only_the_weasyprint_example_is_an_illustration() -> None:
    illustrations = [
        (page, block.body)
        for page in _docs.PAGES
        for block in _markdown_doctest.blocks(_docs.DOCS / page, prefix=_docs.PREFIX)
        if block.kind == "illustration"
    ]
    assert len(illustrations) == 1
    page, body = illustrations[0]
    assert page == "facturx.md"
    assert "weasyprint" in body


def test_every_code_fence_is_python_or_bash() -> None:
    # Only ``python`` fences are run; any other language (or none) would be an example no test executes.
    languages = set()
    for path in _docs.DOCS.rglob("*.md"):
        fences = re.findall(r"^```(.*)$", path.read_text(encoding="utf-8"), re.M)
        assert len(fences) % 2 == 0, path
        assert all(closing == "" for closing in fences[1::2]), path
        languages |= {(path.name, opening) for opening in fences[::2]}
    assert {language for _, language in languages} == {"python", "bash"}, sorted(languages)


def test_the_docs_examples_run_without_artifacts() -> None:
    assert _docs.run(with_artifacts=False) == {
        "quickstart.md": 10,
        "concepts.md": 8,
        "validation.md": 3,
        "facturx.md": 10,
        "mapping/freelancer.md": 11,
        "mapping/ticketing.md": 15,
    }


def render_artifacts_page() -> str:
    """``docs/reference/artifacts.md``: one row per source of the packaged manifest."""
    rows = "\n".join(
        f"| `{source.name}` | {source.version} | {source.license} | <{source.url}> |"
        for source in artifacts.load_manifest().values()
    )
    return f"""# Artifact licences

<!-- Generated by tests/test_docs.py from src/euinvoice/validation/manifest.toml; do not edit.
Run `EUINVOICE_REGEN_DOCS=1 uv run pytest -q tests/test_docs.py` to regenerate. -->

The official validation artifacts and example corpora are third-party works under their own licences. euinvoice
never bundles or redistributes them: `python -m euinvoice artifacts fetch` downloads each archive from its
upstream URL into your cache and checks its sha256 (`src/euinvoice/validation/manifest.toml`). Using them is
subject to the licence of each source.

The licence column is the `license` field of the manifest. The `xrechnung-testsuite` and
`xrechnung-validator-configuration` archives contain no licence file; their entry is the licence recorded in the
manifest for the upstream repository.

| Source | Version | Licence | Download |
|---|---|---|---|
{rows}

euinvoice itself is MIT-licensed. Its runtime dependencies are `pydantic` and `lxml`, plus `saxonche`
(SaxonC-HE, MPL-2.0) with the `[validate]` extra and `pypdf` with the `[pdf]` extra.
"""


def test_artifacts_page_is_current() -> None:
    expected = render_artifacts_page()
    if os.environ.get("EUINVOICE_REGEN_DOCS"):
        ARTIFACTS_PAGE.write_text(expected, encoding="utf-8")
    current = ARTIFACTS_PAGE.read_text(encoding="utf-8") if ARTIFACTS_PAGE.exists() else ""
    assert current == expected, (
        "docs/reference/artifacts.md is stale: run EUINVOICE_REGEN_DOCS=1 pytest tests/test_docs.py"
    )
