"""EN 16931 code lists.

The complete lists live in :mod:`euinvoice.model.codes._generated` (re-exported here), generated by
``scripts/gen_codelists.py`` from the BR-CL-* rules of the pinned CEN code-list Schematron
(``schematron/codelist/EN16931-{UBL,CII}-codes.sch``, validation-1.3.16) and of its syntax binding
files (``schematron/{UBL,CII}/EN16931-*-model.sch``, which bind UBL BR-CL-08). They are what the official
rules accept, so the model validates codes against them.

Where the UBL and CII lists differ, both are generated with a ``_UBL`` / ``_CII`` suffix (or the CII
list keeps the plain name, as :data:`UNTDID_4451_TEXT_SUBJECT`). The syntax-neutral model (D1) accepts
the more permissive list: the union for countries (:data:`ISO_3166_1_COUNTRY`), the CII superset for
note subject codes (:data:`UNTDID_4451_TEXT_SUBJECT` ⊃ :data:`UNTDID_4451_NOTE_SUBJECT_UBL`). The
official per-syntax Schematron stays the oracle (D8) and reports a code the target syntax does not
accept.

Matching: every BR-CL assert except BR-CL-24 (MIME codes) compares ``normalize-space`` of the value, so
strip a value before looking it up. BR-CL-22 (:data:`VATEX_EXEMPTION_REASON`) also upper-cases it:
look up ``code.strip().upper()``.

:mod:`euinvoice.model.codes.derived` holds lists derived from the generated ones, such as the
syntax-neutral :data:`ISO_3166_1_COUNTRY`.

The ``StrEnum`` classes of :mod:`euinvoice.model.codes.enums` are hand-written names for the few codes
the library reasons about. Each is a subset of its generated list (a unit test checks this), and each
member cites where its meaning is stated in the pinned artifacts.
"""

from euinvoice.model.codes._generated import (
    CEF_EAS,
    ISO_3166_1_COUNTRY_CII,
    ISO_3166_1_COUNTRY_UBL,
    ISO_4217_CURRENCY,
    ISO_6523_ICD,
    MIME_CODE,
    PARTY_IDENTIFIER_EXTRA_SCHEME_UBL,
    UNECE_REC20_REC21_UNIT,
    UNTDID_1001_CREDIT_NOTE_TYPE_UBL,
    UNTDID_1001_DOCUMENT_TYPE,
    UNTDID_1001_INVOICE_TYPE_UBL,
    UNTDID_1153_REFERENCE_QUALIFIER,
    UNTDID_2005_VAT_POINT_DATE_UBL,
    UNTDID_2475_VAT_POINT_DATE_CII,
    UNTDID_4451_NOTE_SUBJECT_UBL,
    UNTDID_4451_TEXT_SUBJECT,
    UNTDID_4461_PAYMENT_MEANS,
    UNTDID_5189_ALLOWANCE_REASON,
    UNTDID_5305_VAT_CATEGORY,
    UNTDID_7143_ITEM_CLASSIFICATION,
    UNTDID_7161_CHARGE_REASON,
    VATEX_EXEMPTION_REASON,
)
from euinvoice.model.codes.derived import ISO_3166_1_COUNTRY
from euinvoice.model.codes.enums import DocumentType, VatCategory

__all__ = [
    "CEF_EAS",
    "ISO_3166_1_COUNTRY",
    "ISO_3166_1_COUNTRY_CII",
    "ISO_3166_1_COUNTRY_UBL",
    "ISO_4217_CURRENCY",
    "ISO_6523_ICD",
    "MIME_CODE",
    "PARTY_IDENTIFIER_EXTRA_SCHEME_UBL",
    "UNECE_REC20_REC21_UNIT",
    "UNTDID_1001_CREDIT_NOTE_TYPE_UBL",
    "UNTDID_1001_DOCUMENT_TYPE",
    "UNTDID_1001_INVOICE_TYPE_UBL",
    "UNTDID_1153_REFERENCE_QUALIFIER",
    "UNTDID_2005_VAT_POINT_DATE_UBL",
    "UNTDID_2475_VAT_POINT_DATE_CII",
    "UNTDID_4451_NOTE_SUBJECT_UBL",
    "UNTDID_4451_TEXT_SUBJECT",
    "UNTDID_4461_PAYMENT_MEANS",
    "UNTDID_5189_ALLOWANCE_REASON",
    "UNTDID_5305_VAT_CATEGORY",
    "UNTDID_7143_ITEM_CLASSIFICATION",
    "UNTDID_7161_CHARGE_REASON",
    "VATEX_EXEMPTION_REASON",
    "DocumentType",
    "VatCategory",
]
